### ISSUE TITLE
Incompatibilities

### ISSUE THREAD

**Issue by AndreySolod** [MayamaTakeshi/redmine_rt#20]
This plugin is incompatible with the following plugins:
 - Additionals;
 - Additional Tags - because these plugins request gem 'deface' 1.8.1 and higher, while this plugin requires 1.6.2 (the error correction option does not cause, sample - https://github.com/jbbarth/redmine_base_deface/pull/9/files#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7)
 - redmine_checklists (by RedmineUP) - when update the issue render 500 page - i don't know how to fix it;
 - redmine v.5.0.5:
 1. plugins/redmine_rt/app/views/issues/show.html.erb must be called _show.html.erb;
 2. When I try to use this new field, I cannot save them: The apply button does not work, and I do not know how to fix it

**Comment by MayamaTakeshi** [comment]
Hi, those issues should have been solved.
Please get the latest redmine_rt code.
Also, delete the folder plugins/redmine_base_deface as it is not needed anymore (details: #22)

**Comment by AndreySolod** [comment]
Hi, thank you, but previous version I like more... Because at least I was able to fix it somehow.
Tasks are not displayed now: error 404.
Maybe I should take a non-master branch? I use unicorn instead of puma.
W, [2023-04-19T08:06:45.134461 #155]  WARN -- : [3d47f476-c402-4b43-93fc-cadcbd8c4148] Missing template, responding with 404: Missing template issues/show with {:locale=>[:ru, :en], :formats=>[:html], :variants=>[], :handlers=>[]}. Searched in:
  * "/opt/redmine/plugins/sidebar_hide/app/views"
  * "/opt/redmine/plugins/scrum/app/views"
  * "/opt/redmine/plugins/redmine_x_lightbox2/app/views"
  * "/opt/redmine/plugins/redmine_wysiwyg_editor/app/views"
  * "/opt/redmine/plugins/redmine_theme_changer/app/views"
  * "/opt/redmine/plugins/redmine_status_history/app/views"
  * "/opt/redmine/plugins/redmine_silencer/app/views"
  * "/opt/redmine/plugins/redmine_rt/app/views"
  * "/opt/redmine/plugins/redmine_resources/app/views"
  * "/opt/redmine/plugins/redmine_recurring_tasks/app/views"
  * "/opt/redmine/plugins/redmine_people/app/views"
  * "/opt/redmine/plugins/redmine_monitoring_controlling/app/views"
  * "/opt/redmine/plugins/redmine_logs/app/views"

**Comment by MayamaTakeshi** [comment]
By "Tasks" do you mean something provided by redmine_recurring_tasks?
If yes, I tried to install it but got:
```
$ git clone https://github.com/southbridgeio/redmine_recurring_tasks.git plugins/redmine_recurring_tasks 
Cloning into 'plugins/redmine_recurring_tasks'...
remote: Enumerating objects: 924, done.
remote: Total 924 (delta 0), reused 0 (delta 0), pack-reused 924
Receiving objects: 100% (924/924), 130.08 KiB | 4.06 MiB/s, done.
Resolving deltas: 100% (410/410), done.
$ bundle install
Don't run Bundler as root. Installing your bundle as root will
break this application for all non-root users on this machine.
Fetching https://github.com/moiristo/deep_cloneable.git
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Could not find compatible versions

Because every version of deep_cloneable depends on activerecord >=
3.1.0, < 6
and rails >= 6.1.7.3, < 7.0.0.alpha1 depends on activerecord =
6.1.7.3,
every version of deep_cloneable is incompatible with rails >=
6.1.7.3, < 7.0.0.alpha1.
So, because Gemfile depends on rails = 6.1.7.3
  and Gemfile depends on deep_cloneable >= 0,
  version solving has failed.
```
Are you using a custom version of it?

**Comment by AndreySolod** [comment]
Ok, going to describe my steps here (I build image in Docker, base-image - ubuntu:22.10, ruby is installed by apt-get install ruby ruby_dev)
1) Install nodejs - this solve problem with ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime.
2) Use only plugins Additionals, Additional_tags, redmine_checklists, redmine_rt;
3) Debug tzinfo in main gemfile (gem 'tzinfo-data'#, platforms: [:mingw, :x64_mingw, :mswin]) to solve compatibility issues with unicorn
4) gem 'unicorn' in main gemfile;
5) In docker build - use command "bundle install"
5) commands on start (docker-entrypoint):
```
bundle
RAILS_ENV=production bundle exec rake generate_secret_token
echo "good to Generate Secret Token"
RAILS_ENV=production bundle exec rake db:migrate
echo "good db:migrate"
RAILS_ENV=production bundle exec rake redmine:plugins:migrate
echo "good redmine:plugins:migrate"
exec /usr/bin/supervisord -nc /etc/supervisor/supervisord.conf
supervisord
```
6) run docker compose up: All commands were executed correctly, but I have next error:
INFO exited: unicorn (exit status 1; not expected)
record in unicorn.stderr.log:
```
I, [2023-04-19T10:08:25.308965 #24]  INFO -- : Refreshing Gem list
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get': uninitialized constant Account::Login (NameError)
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `cget'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `each'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `ls'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:297:in `block in eager_load_all'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `each'
	from /var/lib/gems/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `eager_load_all'
	from /var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
	from /var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `run'
	from /var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/application.rb:391:in `initialize!'
	from /opt/redmine/config/environment.rb:16:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from config.ru:4:in `block in <main>'
	from /var/lib/gems/3.0.0/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `instance_eval'
	from /var/lib/gems/3.0.0/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /var/lib/gems/3.0.0/gems/unicorn-6.1.0/lib/unicorn.rb:54:in `eval'
	from /var/lib/gems/3.0.0/gems/unicorn-6.1.0/lib/unicorn.rb:54:in `block in builder'
	from /var/lib/gems/3.0.0/gems/unicorn-6.1.0/bin/unicorn_rails:139:in `block in rails_builder'
	from /var/lib/gems/3.0.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:821:in `build_app!'
	from /var/lib/gems/3.0.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:140:in `start'
	from /var/lib/gems/3.0.0/gems/unicorn-6.1.0/bin/unicorn_rails:209:in `<top (required)>'
	from /usr/local/bin/unicorn_rails:25:in `load'
	from /usr/local/bin/unicorn_rails:25:in `<main>'
```
But, when I use plugin redmine_base_deface and change "gem 'deface', 1.9.0", I get the following result:
... Hey, all start and work correctly!
Apparently, this is an incompatibility of some plugins.
The plugin was calculated by the exclusion method - this is onlyoffice_redmine.
It's funny, this is one of the most powerful and most controversial plugins - it works on the ubuntu host machine, but refuses to work on debian (docker images behave differently), and despite a lot of effort spent on it, it will have to be abandoned. It's really a pity: I broke my brain while trying to figure out how it resolves dns in docker.
All out in production.log:
```
I, [2023-04-19T10:28:33.702186 #21]  INFO -- : [c2bf1a57-a5bd-4bbe-a9d3-4ed7853b713f] Completed 200 OK in 204ms (Views: 151.5ms | ActiveRecord: 45.2ms | Allocations: 88035)
I, [2023-04-19T10:28:35.315023 #21]  INFO -- : [84239eb2-7df0-4b8d-8e1d-d8978144e12e] Started GET "/issues/1" for 172.18.0.1 at 2023-04-19 10:28:35 +0000
I, [2023-04-19T10:28:35.315876 #21]  INFO -- : [84239eb2-7df0-4b8d-8e1d-d8978144e12e] Processing by IssuesController#show as HTML
I, [2023-04-19T10:28:35.315950 #21]  INFO -- : [84239eb2-7df0-4b8d-8e1d-d8978144e12e]   Parameters: {"id"=>"1"}
I, [2023-04-19T10:28:35.321359 #21]  INFO -- : [84239eb2-7df0-4b8d-8e1d-d8978144e12e]   Current user: admin (id=1)
E, [2023-04-19T10:28:35.445329 #21] ERROR -- : [84239eb2-7df0-4b8d-8e1d-d8978144e12e] [1;32mDeface:[0m 'force history always' matched 0 times with '#history'
E, [2023-04-19T10:28:35.445976 #21] ERROR -- : [84239eb2-7df0-4b8d-8e1d-d8978144e12e] [1;32mDeface:[0m 'add quick notes' matched 0 times with '#history'
I, [2023-04-19T10:28:35.449115 #21]  INFO -- : [84239eb2-7df0-4b8d-8e1d-d8978144e12e]   Rendered plugins/onlyoffice_redmine/app/views/issues/show.html.erb within layouts/base (Duration: 5.0ms | Allocations: 4487)
I, [2023-04-19T10:28:35.449329 #21]  INFO -- : [84239eb2-7df0-4b8d-8e1d-d8978144e12e]   Rendered layout layouts/base.html.erb (Duration: 5.3ms | Allocations: 4521)
W, [2023-04-19T10:28:35.449992 #21]  WARN -- : [84239eb2-7df0-4b8d-8e1d-d8978144e12e] Missing template, responding with 404: Missing template issues/show with {:locale=>[:ru, :en], :formats=>[:html], :variants=>[], :handlers=>[]}. Searched in:
  * "/opt/redmine/plugins/redmine_rt/app/views"
  * "/opt/redmine/plugins/redmine_checklists/app/views"
  * "/opt/redmine/plugins/redmine_banner/app/views"
  * "/opt/redmine/plugins/redmine_agile/app/views"
  * "/opt/redmine/plugins/onlyoffice_redmine/app/views"
  * "/opt/redmine/plugins/additionals/app/views"
  * "/opt/redmine/plugins/additional_tags/app/views"
  * "/opt/redmine/app/views"
  * "/var/lib/gems/3.0.0/gems/redmine_crm-0.0.59/app/views"
  * "/var/lib/gems/3.0.0/gems/render_async-2.1.11/app/views"
  * "/opt/redmine/plugins/additionals/app/views"
  * "/opt/redmine/plugins/additional_tags/app/views"
```

About redmine_recurring_tasks - yes, this is this plugin, and I upgraded it a little so that the assembly was done correctly. But I installed it only yesterday, and I upgraded it incorrectly: I just replaced all the paths in require with absolute paths (for example, "require 'redmine_recurring_task'" became "require'/opt/redmine/plugins/redmine_recurring_task/lib/redmine_recurring_task'", etc.).
Thanks again for the help, but the redmine_base_deface plugin is still needed - don't delete it from the readme yet.

**Comment by MayamaTakeshi** [comment]
I did a quick smoke test with unicorn and it works when I only have these installed:
```
$ ls plugins/
additionals  additional_tags  README  redmine_checklists  redmine_rt
```
I suspect this is not a problem with redmine_rt.
Have you tried installing plugins one-by-one?
If you remove redmine_rt everything works fine?

**Comment by AndreySolod** [comment]
> If you remove redmine_rt everything works fine?

Yes, if I remove redmine_rt everything works fine.

> Have you tried installing plugins one-by-one?

Yes, that's what I usually do - I install one plugin at a time, assemble the image and see if everything has got up correctly
If I install only redmine_rt - I have a problem with unicorn.

> I suspect this is not a problem with redmine_rt.

It can be:
- The problem with docker itself (never encountered);
- A problem with the host on which the application is running (the same container behaves completely differently on the debian host and on the ubuntu host, and sometimes significantly differently)
- There may be a problem with the unicorn configuration. Once upon a time on the Internet I found the following recommended configuration:

```app_dir = File.expand_path("../..", __FILE__)
shared_dir = "#{app_dir}/shared"
working_directory app_dir
 
worker_processes 2
preload_app true
timeout 30
 
listen "#{shared_dir}/sockets/unicorn.sock", :backlog => 64

stderr_path "#{shared_dir}/log/unicorn.stderr.log"
stdout_path "#{shared_dir}/log/unicorn.stdout.log"
 
pid "#{shared_dir}/pids/unicorn.pid"
 
before_fork do |server, worker|
    defined?(ActiveRecord::Base) and
        ActiveRecord::Base.connection.disconnect!
end
 
after_fork do |server, worker|
    defined?(ActiveRecord::Base) and
        ActiveRecord::Base.establish_connection
end
```

unicorn command:
`unicorn_rails -c ./config/unicorn.rb -E production`

What unicorn configuration do you use?

**Comment by MayamaTakeshi** [comment]
It is not related to unicorn (just for the record, I used this: https://github.com/MayamaTakeshi/redmine_rt/blob/master/dev_utils/setup_unicorn_for_dev_work.sh)

I was able to recreate the problem with just this:
```
$ bundle exec rails server -e production -b 0.0.0.0
...ABRIDGED...
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get': uninitialized constant Account::Login (NameError)
```
It only happens if environment is production. Using development is OK.
This was OK before so something got broken with the latest new changes.
I will try to solve it but it may take time.

**Comment by MayamaTakeshi** [comment]
OK. The difference between development and production is this:
```
$ grep eager_load config/environments/development.rb 
  config.eager_load = false

$ grep eager_load config/environments/production.rb 
  config.eager_load = true
```
If I change production to eager_load false the problem doesn't happen but this is bad because it will impact performance.
Anyway I think it might be something with redmine_plugin_kit.

**Comment by MayamaTakeshi** [comment]
OK. Indeed it is an issue with redmine_plugin_kit. Maybe I am missing something when replacing redmine_base_deface with it.
Meanwhile I have reverted to use redmine_base_deface.
Please get latest code and try again.

**Comment by MayamaTakeshi** [comment]
Indeed there was missing code required to work with redmine_plugin_kit.
I think the issue was solved in #22.  Tested with development and production environments and both looked OK.
Now I don't use redmine_base_deface anymore.

**Comment by AndreySolod** [comment]
Hi, thanks for editing the plugin, it was useful, including for me - now I know how to fix other plugins.
I still have a little question: what about adding a comment without reloading the page (as in the description) - do you need any additional libraries or settings for this? Is it possible to specify them in the Readme?
I use next Docker-image command to install all libraries and gems:
```
FROM ubuntu:22.10

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y curl apt-utils ruby3.1 ruby3.1-dev ruby-dev ruby xapian-omega ruby-xapian libxapian-dev poppler-utils antiword  unzip catdoc libwpd-tools libwps-tools gzip unrtf catdvi djview djview3 uuid uuid-dev xz-utils libemail-outlook-message-perl rubygems rubygems-integration libpq-dev build-essential patch zlib1g-dev liblzma-dev imagemagick nano vim gsfonts git subversion bzr gcc g++ ghostscript supervisor cron libreoffice liblibreoffice-java nodejs npm

#RUN update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby3.1 10 # Forwarding Default Ruby on 3.1.2
#RUN update-alternatives --install /usr/bin/gem gem /usr/bin/gem3.1 10 # do not uncomment to support DMSF plugin
RUN gem install bundler unicorn nokogiri rake
RUN gem install rails -v 6.1.7.2
RUN gem install pg -v 1.2.3
RUN gem install execjs
#RUN gem install xapian-ruby

COPY redmine-5.0.5 /opt/redmine/

WORKDIR /opt/redmine/

RUN bundle install
```

**Comment by MayamaTakeshi** [comment]
All instructions are in the README.
Your Dockerfile is missing installation of redis:
```
  apt install -y redis-server
```
And you need to have a config/cable.yml like this:
```
development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: redmine_rt

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: redmine_rt
```
Redis is used to distribute the update events to the browsers.
The Issue tab in the browser gets notified of changes in history and adds/removes/updates notes accordingly.
Obs: redis is not exposed to clients. The Rails Cable infrastructure talks with the browsers using WebSockets and relays events received from redis.

**Comment by AndreySolod** [comment]
I have the redis, but in another container in network mainNetwork.
My config/cable.yml file is:
```
development:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: redmine_rt

test:
  adapter: async

production:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: redmine_rt

```
... Sorry, the problem was solved, but I do not know how.
I did 2 things:
- Added the npm package in Dockerfile;
- Updated the ubuntu host kernel to 23.04.
Maybe after a few tests I'll figure out what the problem was and write here.

**Comment by MayamaTakeshi** [comment]
If you tried to test the addition of comments immediately after reloading the Issue tab in the browser, maybe the Issue was not updated in the browser because the WebSocket connection was not established yet (it should be up after some seconds). I have opened a ticket to check this later #29.
